In [7]:
from scipy import linalg
import scipy
import numpy as np

## Kn

In [15]:
K = scipy.linalg.toeplitz([2,-1,0,0,0,0,0,0])

In [16]:
print(K)

[[ 2 -1  0  0  0  0  0  0]
 [-1  2 -1  0  0  0  0  0]
 [ 0 -1  2 -1  0  0  0  0]
 [ 0  0 -1  2 -1  0  0  0]
 [ 0  0  0 -1  2 -1  0  0]
 [ 0  0  0  0 -1  2 -1  0]
 [ 0  0  0  0  0 -1  2 -1]
 [ 0  0  0  0  0  0 -1  2]]


## Cn

In [4]:
C = scipy.linalg.toeplitz([2,-1,0,-1])

In [5]:
print(C)

[[ 2 -1  0 -1]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [-1  0 -1  2]]
